// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Puzzle.Data;

namespace SudokuApp.Data.Migrations
{
    [DbContext(typeof(PuzzleContext))]
    [Migration("20200604184054_CreateDatabase")]
    partial class CreateDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("Puzzle.Models.PuzzleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Solved")
                        .HasColumnName("Solved")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Puzzles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Solved = true
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
